// Gemini Imagen client for image generation
// Note: Using placeholder - actual API may differ

export interface GenerateImageOptions {
  prompt: string;
  style?: string;
  count?: number;
}

export interface GeneratedImage {
  buffer: Buffer;
  prompt: string;
  style: string;
}

const STYLE_MODIFIERS: Record<string, string> = {
  whiteboard: 'hand-drawn whiteboard sketch style, markers on white background, casual and explanatory',
  isometric: '3D isometric technical illustration, clean vectors, modern tech aesthetic',
  infographic: 'bold infographic style, vibrant colors, icons and data visualization',
  abstract: 'conceptual abstract art, gradient meshes, floating elements, artistic',
  blueprint: 'technical blueprint style, dark blue background, white and cyan lines',
  minimalist: 'minimalist icon style, simple shapes, limited color palette',
  retro: 'vintage technical illustration, cross-sections with labels, educational',
  darkmode: 'dark mode UI style, dark background, neon accents, glass morphism',
};

export async function generateImages(options: GenerateImageOptions): Promise<GeneratedImage[]> {
  const { prompt, style = 'minimalist', count = 4 } = options;

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error('GEMINI_API_KEY environment variable is not set');
  }

  // Validate count (API supports 1-4 images)
  const imageCount = Math.max(1, Math.min(4, count));

  const styleModifier = STYLE_MODIFIERS[style] || STYLE_MODIFIERS.minimalist;
  const fullPrompt = `${prompt}. Style: ${styleModifier}`;

  console.log('Image generation prompt:', fullPrompt);
  console.log('Requested count:', imageCount);

  try {
    // Using Imagen 3 API endpoint
    const response = await fetch(
      'https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict',
      {
        method: 'POST',
        headers: {
          'x-goog-api-key': apiKey,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          instances: [
            {
              prompt: fullPrompt,
            },
          ],
          parameters: {
            sampleCount: imageCount,
            aspectRatio: '1:1',
            personGeneration: 'allow_adult',
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(
        `Gemini API request failed with status ${response.status}: ${errorText}`
      );
    }

    const data = await response.json();

    // Parse response and extract images
    const predictions = data.predictions || [];
    const generatedImages: GeneratedImage[] = [];

    for (const prediction of predictions) {
      if (prediction.bytesBase64Encoded) {
        const buffer = Buffer.from(prediction.bytesBase64Encoded, 'base64');
        generatedImages.push({
          buffer,
          prompt: fullPrompt,
          style,
        });
      }
    }

    if (generatedImages.length === 0) {
      throw new Error('No images were generated by the API');
    }

    console.log(`Successfully generated ${generatedImages.length} images`);
    return generatedImages;
  } catch (error) {
    console.error('Error generating images with Gemini:', error);
    throw error;
  }
}

export function getAvailableStyles(): string[] {
  return Object.keys(STYLE_MODIFIERS);
}

export function buildImagePrompt(description: string, style: string): string {
  const styleModifier = STYLE_MODIFIERS[style] || '';
  return `${description}. ${styleModifier}`.trim();
}
